events {}

http {
  upstream user_service {
    server user-service:4000;
  }

  upstream post_service {
    server post-service:5000;
  }

  server {
    listen 80;

    location /users {
      proxy_pass http://user_service;
    }

    location /posts {
      proxy_pass http://post_service;
    }
  }
}
